version: 0.0
os: linux
overwrite: true
files:
  - source: /
    destination: /home/ec2-user/nodejs-aws-codedeploy-pipeline
    permissions:
      - object: "*"
        pattern: overwrite
file_exists_behavior: OVERWRITE
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
# ValidateService:
